add_newline = true
format = """$username$directory$character"""
right_format = """$all"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
read_only = " 󰌾"
style = "bold yellow"

[docker_context]
symbol = " "

[gcloud]
disabled = true

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_status]
modified = " 🛠️"
stashed = " 📦"
ahead = " 🏎️"
behind = " 🐢"
diverged = " 🔱"

[git_commit]
tag_symbol = '  '

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
disabled = true
symbol = "󰍛 "

[nim]
symbol = "󰆥 "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Debian = " "
Linux = " "
Macos = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Ubuntu = " "
Unknown = " "

[python]
symbol = " "

[package]
symbol = "󰏗 "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[time]
format = "🕙 [$time]($style) "
time_format = "%T"
disabled = true

[kubernetes]
disabled = false
symbol = "󱃾 "
format = '[$symbol$context( \($namespace\))]($style) '
style = "cyan bold"

[custom.vpn]
disabled = false
command = "ifconfig tun0 | grep 'inet ' | awk '{print $2}' || ip -4 addr show tun0 | grep -oP '(?<=inet\\s)\\d+(\\.\\d+){3}'"
when = "ifconfig tun0 || ip a show tun0"
symbol = " "
style = "bold red"
format = "[$symbol$output]($style) "

[cmd_duration]
min_time = 2_000
format = " [⏳ $duration]($style)"
style = "bold yellow"

[username]
show_always = true
format = "[\\[$user\\]]($style) "
style_user = "bold blue"
style_root = "bold red"